# Generated by Django 4.2.6 on 2023-10-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userforge_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userforge',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
